<?php 
echo $this->headLink();
echo $this->headTitle();
echo $this->headScript();
?>

<div style="position:absolute;left:10px;top:0px">
	<table class='display' style='width:100px;left:250px'>
			<?= $this->placeholder('installerdashboard');?>
	</table>
</div>

	<table border='0' style='width:1150px'>
	<tr>
	<td align='center' style='font-size:18; color:#0E598C;'>Actions</td>
	</tr>
	<tr class='header'>
	<td>Schedule</td><td>Something</td><td>Tools</td><td>Fun</td>
	<td>Something</td><td>Something</td><td>Something</td><td>Something</td>
	</tr>
	<tr>
 	<td><a href='/fieldinstallation/appointments/'>Todays Appointments</a></td>
 	<td>Something</td><td>Something</td><td>Something</td>
 	<td>Something</td><td>Something</td>
 	<td>Something</td><td>Something</td>
 	</tr>