<?php 
echo $this->headLink();
echo $this->headTitle();
echo $this->headScript();
?>

<script type="text/javascript">

$(function(){

	var building_id = "undefined";

	$('select#building_id').bind('change',function(){

		building_id = $(this).val();
		
		$.ajax({
			url:"/unit/getinfrastructureunitsfrombuildingdropdownajax/",
			data:'building_id='+$(this).val(),
			async: false,
	    	success: function(data){
	    		$('select#unit_id').html(data);
	    	}
		});  
	});

	
	

	$('input#addproject').bind('click',function(){
		windowW = 550;
		windowH = 450;
		x    = (screen.width/2)-(windowW/2);
		y    = (screen.height/2)-(windowH/2);
		window.open('/project/create', 'popup5', 'width='+windowW+', height='+windowH+', menubar=no, scrollbars=no, toolbar=no, location=no, status=yes, resizable=no, top='+y+', left='+x);
	});

	$('input#addbuilding').bind('click',function(){
		windowW = 550;
		windowH = 450;
		x    = (screen.width/2)-(windowW/2);
		y    = (screen.height/2)-(windowH/2);
		window.open('/building/create', 'popup5', 'width='+windowW+', height='+windowH+', menubar=no, scrollbars=no, toolbar=no, location=no, status=yes, resizable=no, top='+y+', left='+x);
	});

	$('input#addsingleunit').bind('click',function(){
		windowW = 550;
		windowH = 450;
		x    = (screen.width/2)-(windowW/2);
		y    = (screen.height/2)-(windowH/2);
		window.open('/building/addsingleunit/?building_id='+building_id, 'popup5', 'width='+windowW+', height='+windowH+', menubar=no, scrollbars=no, toolbar=no, location=no, status=yes, resizable=no, top='+y+', left='+x);
	});

});

</script>



<div style='position:absolute;width:100%;height:100%'>
	
	<div style="position: absolute;left:0px;top:0px;">
	
	<form autocomplete="off" method='post' action="">
	
		<?php echo $this->addactiveequipmenttoinventoryform;?>
		
		</form>
		
		<input type='button' id='addproject' class='button' value='New Project'></input>
		<input type='button' id='addbuilding' class='button' value='New Building'></input>
		<input type='button' id='addsingleunit' class='button' value='New Unit'></input>
		
		<?php echo $this->error;?>
	</div>
</div>