<?php $this->headLink()->appendStylesheet('/css/connections.css');?>
<?php $this->headScript()->appendFile('/javascripts/global/inventory.js');?>

<?php $this->headScript()->appendFile('/javascripts/global/jquery/jquery.jsPlumb-1.3.6-all-min.js');?>

<?php $this->headScript()->appendFile('/javascripts/interfaceconnections.js');?>



	<div id="sub_menu">
		<div id="add_baidiplexer" class="submenu">Add New BAI Diplexer</div>
		<div id="add_equipment" class="submenu">Add Equipment</div>
		
	</div>
	<div id="jquery_contextmenu" style="background-color: #F0F0F0; position: absolute; width: 100px; height: 20px; border: 1px solid black; border-radius:0px;">
	<span style="font-size: x-small; text-align: left">Show Connection</span>
	</div>
