<?php 
echo $this->headLink();
echo $this->headTitle();
echo $this->headScript();
?>

<script type='text/javascript'>
$(function(){
	$('input#addpurchaseorderitem').bind('click',function(){
		windowW = 760;
		windowH = 520;
		x    = (screen.width/2)-(windowW/2);
		y    = (screen.height/2)-(windowH/2);
		window.open('/purchasing/addpurchaseorderitem/?po_id=<?php echo $_GET["po_id"]?>', 'popup2', 'width='+windowW+', height='+windowH+', menubar=no, scrollbars=yes, toolbar=no, location=no, status=yes, resizable=no, top='+y+', left='+x);
	});
	$('input#editpurchaseorderitem').live('click',function(){
		windowW = 760;
		windowH = 520;
		x    = (screen.width/2)-(windowW/2);
		y    = (screen.height/2)-(windowH/2);
		po_item_id = $(this).attr('po_item_id');
		window.open('/purchasing/editpurchaseorderitem/?po_id=<?php echo $_GET["po_id"]?>&po_item_id='+po_item_id, 'popup2', 'width='+windowW+', height='+windowH+', menubar=no, scrollbars=yes, toolbar=no, location=no, status=yes, resizable=no, top='+y+', left='+x);
	});
	
});
</script>
<script type="text/javascript">
var datefield=document.createElement("input")
datefield.setAttribute("type", "date")
if (datefield.type!="date"){ //if browser doesn't support input type="date", load files for jQuery UI Date Picker
    document.write('<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />\n')
    document.write('<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"><\/script>\n')
    document.write('<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"><\/script>\n')
}
</script>

<script>
if (datefield.type!="date"){ 
jQuery(function($){ //on document.ready
    $('#order_date').datepicker({dateFormat: 'yy-mm-dd'});
})
}
</script>





<div style="position:absolute;width:1250px;height:800px">
	<div style="position:absolute;left:10px;top:10px">
		<?php echo $this->placeholder('purchasing_menu');?>
	</div>
	
	<form method='post' action=''>
	<div style="position:absolute;left:10px;top:50px">
		PO Number: <input type="text" class="text" name='po_number' style="width:150px" value="<?php echo $this->po_number?>"></input>
	</div>
	<div style="position:absolute;left:250px;top:50px">
		Create Date: <input type="readonly" class="text" name='createdate' style="width:150px" value="<?php echo $this->create_date?>"></input>
	</div>
		<div style="position:absolute;left:490px;top:50px">
		Creator: <input type="readonly" class="text" name='creator' style="width:150px" value="<?php echo $this->creator?>"></input>
	</div>
	<div style="position:absolute;left:710px;top:50px">
		Status: <input type="text" class="text" name='po_status' style="width:150px" value="<?php echo $this->po_status?>"></input>
	</div>
	<div style="position:absolute;left:920px;top:50px">
		<input type='submit' class='button' value='Save'></input>
	</div>

	<div style="position:absolute;left:10px;top:90px">
		PO Subject: <input type="text" class="text" name='po_subject' style="width:150px" value="<?php echo $this->po_subject?>"></input>
	</div>
	<div style="position:absolute;left:252px;top:90px">
		Order Date: <input type="date" id='order_date' class="text" name='order_date' style="width:150px" value="<?php echo $this->order_date?>"></input>
	</div>
	<div style="position:absolute;left:500px;top:90px">
		Terms: <?php echo $this->po_terms_dd?>
	</div>
	<div style="position:absolute;left:702px;top:90px">
		Vendor: <?php echo $this->vendor_dd?>
	</div>
	
	<div style="position:absolute;left:38px;top:130px">
		Freight: <?php echo $this->po_freight_dd?>
	</div>
	<div style="position:absolute;left:238px;top:130px">
		Shipping Cost: <input type="text" class="text" name='shipping_cost' style="width:150px" value="<?php echo $this->shipping_cost?>"></input>
	</div>
		
	<div style="position:absolute;left:498px;top:130px">
		Status: <input type="text" class="text" name='po_lock' style="width:150px" value="<?php echo $this->po_lock?>"></input>
	</div>
	<div style="position:absolute;left:750px;top:130px">
			<?php echo $this->download_create_po?>
	</div>

	<div style="position:absolute;left:0px;top:180px">
			<?php echo $this->po_item_list;	?>
			
		</table>
	</div>

</div>