<?php 
echo $this->headLink();
echo $this->headTitle();
echo $this->headScript();
?>

<script type='text/javascript'>
$(function(){

});
</script>



<div style="position:absolute;width:1250px;height:800px">
	<div style="position:absolute;left:10px;top:10px">
		<?php echo $this->placeholder('purchasing_menu');?>
	</div>
<div style="position:absolute;top:60px;">
		<?php echo $this->placeholder('purchase_order_table');?>
</div>
</div>