<?php 
echo $this->headLink();
echo $this->headTitle();
echo $this->headScript();
?>


<script type='text/javascript'>
$(function(){
	
	
});
</script>

<form method="post" action="" name="syncinterfaceconfig">
<center>
<table border=1>

<tr><td colspan=2><b>Confirm Override you are about to sync:</b><br></td></tr>

<tr><td>Device:</td><td> <?= $this->equipment_fqdn;?></td></tr>
<tr><td>Serial number:</td><td><?= $this->equipment_serial;?></td></tr>
<tr><td>Application Name:</td><td><?= $this->application_name;?></td></tr>
<tr><td colspan=2>Details:</td></tr>
<tr><td colspan=2><textarea rows='4' cols='50'><?= $this->details;?></textarea></td></tr>

<tr><td colspan=2><center><input type='submit' value='Sync' /></center></td></tr>

</table>
</center>
<input type='hidden' name='equipment_application_map_id' value='<?= $_GET['equipment_application_map_id'];?>'></input>
</form>