<?php $this->headScript()->appendFile('/javascripts/inventory/addequipment.js');?>
<html>
		<body onLoad="document.forms.addinveq.eq_serial.focus()">
		
		<br><br><br><br><br>
		
		<table align='center' width='1175px' cellpadding="10" border="2px" bordercolor="#CCCCCC" rules="none" class="bodytext" style="padding-top:10px">
		
		<form name='addinveq' action="/equipment/testcreatevlanoninterface" method="post">
		
		<tr>
		<td>
		Equipment ID:
		</td>
		<td>
		<input size='35' type='text' name='eq_id' value='16'>
		</td>
		</tr>
		
		<tr>
		<td>
		Interface ID:
		</td>
		<td>
		<input size='35' type='text' name='if_id' value='114'>
		</td>
		</tr>
		
		<tr>
		<td>
		VLAN Type:
		</td>
		<td>
		<input size='35' type='text' name='vlan_type' value='trunk'>
		</td>
		</tr>
		
		<tr>
		<td>
		VLAN ID:
		</td>
		<td>
		<input size='35' type='text' name='vlan_id' value=''>
		</td>
		</tr>
		
		
		<tr>
		<td>
		</td>
		<td>
		<input type="submit" value="Create VLAN" />
		</td>
		</tr>
		</form>
		
		
		</table>
		</body>
		</html>